#!/usr/bin/env python
# -*- coding: utf-8 -*-

import math
import time
import rospy
import std_msgs
import sensor_msgs
import geometry_msgs
from geometry_msgs.msg import Point
import arom
import axis
import json
from __init__ import AromNode


class SolarLab(AromNode):
    node_name = "demo_hbstep"
    node_type = "demo_hbstep"
    node_pymlab = True

    def __init__(self):


        rospy.Subscriber("/arom/UI/buttons", std_msgs.msg.String, self.callback_btn)


        self.pub_motor_a = rospy.Publisher("/coleostat/motor_a", std_msgs.msg.String, queue_size=1)

        AromNode.__init__(self)
        #self.pymlab = rospy.ServiceProxy('pymlab_drive', arom.srv.PymlabDrive)

        self.set_feature('hbstep_status',  {'id': 'motor_a', 'name': 'Motor RA', 'toppic': '/coleostat/motor_a'})
        #self.set_feature('hsfa_speed',{'param': '/coelostat/speeds/tracking'})

        
        rospy.Timer(rospy.Duration(1), self.get_status, oneshot=False)
        # spusteni funkce (self.getstatus), ktera bude periodicky volana (T=1s). 

        self.motor_a = axis.axis(SPI = self.pymlab, SPI_CS = 0b0001, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = 'spi')
        self.motor_a.Reset(KVAL_RUN = 0xE0, KVAL_ACC = 0xE0, KVAL_DEC = 0xE0, FS_SPD = 0xFFFF)
        #self.motor_a.setConfig(EXT_CLK = 0b1, OSC_SEL = 0b110) # Ext clock source: 24 MHz(Crystal/resonator driver disabled)
        self.motor_a.Float()
        self.motor_a.MaxSpeed(0x33FF)


        last_data = [None]

        while not rospy.is_shutdown():
            try:
                self.motor_a.Run(1, 100)
                time.sleep(5)
                self.motor_a.Run(1, -100)
                time.sleep(5)
                self.motor_a.GoHome()
                time.sleep(2)
            except Exception, e:
                print "err1>", e


        self.motor_a.Float()

    def get_status(self, timer):
        try:
            self.motor_a_status = self.motor_a.GetStatus()
            #print self.motor_a_status, self.motor_b_status, self.motor_c_status
            self.pub_motor_a.publish(json.dumps(self.motor_a_status, ensure_ascii=False))
            

        except Exception as e:
            print 'err2> ', e



    def callback_btn(self, recive):
        #print recive
        self.btn_data.append(recive.data)
        #print recive, btn_data



if __name__ == '__main__':
    m = SolarLab()
