#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
import std_msgs
import pylirc
from __init__ import AromNode


class irUI(AromNode):
    node_name = "irUI"
    node_type = "irUI"

    def __init__(self, name = "irUI"):
        self.pub_btn = rospy.Publisher('/arom/UI/buttons', std_msgs.msg.String, queue_size=10)
        self.pub_beep = rospy.Publisher('/beeper/preset', std_msgs.msg.String, queue_size=5)

        AromNode.__init__(self)
        self.set_feature('irRemote',{'type': "odroid"})
        blocking = 0;

        rate = rospy.Rate(10)
        pylirc.init("pylirc", "/home/odroid/robozor/station/irConf.conf", blocking)
        while not rospy.is_shutdown():
            try:
                s = pylirc.nextcode(1)
                if s:
                    rospy.loginfo(s[0]['config'])
                    self.pub_btn.publish(s[0]['config'])
                    self.pub_beep.publish('btn')
                s = []

            except Exception, e:
                rospy.logerr(e)
            rate.sleep()

        pylirc.exit()
        self.connection.close()


if __name__ == '__main__':
    m = irUI()

