#!/usr/bin/env python
# -*- coding: utf-8 -*-

import math
import time
import rospy
import std_msgs
import sensor_msgs
import geometry_msgs
from geometry_msgs.msg import Point
import arom
import axis
import json
from __init__ import AromNode

btn_data = []

def callback_btn(recive):
    print recive
    global btn_data
    btn_data.append(recive.data)
    #print recive, btn_data


class SolarLab(AromNode):
    node_name = "sun_controller"
    node_type = "asu_solar"
    node_pymlab = True
    flag = {'tracking': False}

    def __init__(self):

        self.speedA = 0
        self.speedB = 0
        self.speedC = 0
        spdAold, spdBold = 0, 0
        self.trackingSpdDefault = int(rospy.get_param("/coelostat/speeds/tracking", 100))
        self.trackingSpd = self.trackingSpdDefault
        self.sunpos = None
        self.btn_data = []

        rospy.Subscriber("/arom/UI/buttons", std_msgs.msg.String, self.callback_btn)
        rospy.Subscriber("/sun_pos", Point, self.callback_sunpos)
        rospy.Subscriber("/sun_err", Point, self.callback_sunerr)

        self.pub_imagetarget = rospy.Publisher("/image_target", Point, queue_size=1)
        self.pub_imagecommand= rospy.Publisher("/image_command", std_msgs.msg.String, queue_size=5)
        self.pub_beep = rospy.Publisher('/beeper/preset', std_msgs.msg.String, queue_size=5)
        self.pub_lcd  = rospy.Publisher('/arom/node/lcd_client/rows', std_msgs.msg.String)


        self.pub_motor_a = rospy.Publisher("/coleostat/motor_a", std_msgs.msg.String, queue_size=1)
        self.pub_motor_b = rospy.Publisher("/coleostat/motor_b", std_msgs.msg.String, queue_size=1)
        self.pub_motor_c = rospy.Publisher("/coleostat/motor_c", std_msgs.msg.String, queue_size=1)

        #rospy.Subscriber("sun_pos", geometry_msgs.msg.Point, self.callback_sunpos)


        AromNode.__init__(self)
        self.pymlab = rospy.ServiceProxy('pymlab_drive', arom.srv.PymlabDrive)
        #self.set_feature('gpio_set_port',{'ports': 8, 'devices': str(self.devices0) ,'subscrib': '/gpio/gpio_mount'})
        #self.set_feature('gpio_all_off',{'subscrib': '/gpio/gpio_mount', 'msg': 'off'})

        self.set_feature('hbstep_status',  {'id': 'motor_a', 'name': 'Motor RA', 'toppic': '/coleostat/motor_a'})
        self.set_feature('hbstep_status__0', {'id': 'motor_b', 'name': 'Motor DEC', 'toppic': '/coleostat/motor_b'})
        self.set_feature('hbstep_status__1',{'id': 'motor_c', 'name': 'Motor Time', 'toppic': '/coleostat/motor_c'})
        self.set_feature('hsfa_speed',{'param': '/coelostat/speeds/tracking'})

        #self.pymlab(device="gpio_mount", method="config_ports", parameters=str(dict(port0 = self.config0, port1 = self.config1)))
        
        rospy.Timer(rospy.Duration(2), self.get_status, oneshot=False)

        self.motor_a = axis.axis(SPI = self.pymlab, SPI_CS = 0b0001, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = 'mirrorRADEC')
        self.motor_b = axis.axis(SPI = self.pymlab, SPI_CS = 0b0010, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = 'mirrorRADEC')
        self.motor_c = axis.axis(SPI = self.pymlab, SPI_CS = 0b0100, Direction = True, StepsPerUnit = 1, protocol = 'arom', arom_spi_name = 'mirrorTIME')

        #self.motor_a.Reset()
        #self.motor_b.Reset()
        #self.motor_c.Reset()

        self.motor_a.Float()
        self.motor_b.Float()
        self.motor_c.Float()
        last_data = [None]

        rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            try:
                if len(self.btn_data) > 0:
                    print self.btn_data[0], len(self.btn_data)
                    lastBtn = self.btn_data[0]
                    last_data = lastBtn.split(" ")
                    self.btn_data.pop(0)

                    print "incomming:", last_data

                    if last_data[0] == 'KEY_LEFT':
                        self.speedA -= 10
                        self.motor_a.Run(0, self.speedA)
                        #time.sleep(0.25)
                        self.flag['tracking']= False
                        self.pub_imagecommand.publish("pause")
                        self.pub_lcd.publish("Left \n %s" %(self.speedA))

                    elif last_data[0] == 'KEY_RIGHT':
                        self.speedA += 10
                        self.motor_a.Run(0, self.speedA)
                        #time.sleep(0.25)
                        self.flag['tracking']= False
                        self.pub_imagecommand.publish("pause")
                        self.pub_lcd.publish("Right \n %s" %(self.speedA))

                    elif last_data[0] == 'KEY_UP':
                        self.speedB -= 10
                        self.motor_b.Run(0, self.speedB)
                        #time.sleep(0.25)
                        self.flag['tracking']= False
                        self.pub_imagecommand.publish("pause")
                        self.pub_lcd.publish("Up \n %s" %(self.speedB))

                    elif last_data[0] == 'KEY_DOWN':
                        self.speedB += 10
                        self.motor_b.Run(0, self.speedB)
                        #time.sleep(0.25)
                        self.flag['tracking']= False
                        self.pub_imagecommand.publish("pause")
                        self.pub_lcd.publish("Down \n %s" %(self.speedB))

                    elif last_data[0] == 'KEY_VOLUMEUP':
                        self.flag['tracking']= False
                        self.pub_imagecommand.publish("pause")
                        self.trackingSpd += 10
                        self.motor_c.Run(0, self.trackingSpd)
                        #time.sleep(0.25)

                    elif last_data[0] == 'KEY_VOLUMEDOWN':
                        self.flag['tracking']= False
                        self.pub_imagecommand.publish("pause")
                        self.trackingSpd -= 10
                        self.motor_c.Run(0, self.trackingSpd)
                        #time.sleep(0.25)

                    elif last_data[0] == 'KEY_OK':
                        self.flag['tracking']= True
                        print self.sunpos
                        if self.sunpos:
                            self.pub_imagetarget.publish(self.sunpos)
                        self.speedA = 0
                        self.speedB = 0
                        self.motor_a.Run(0, self.speedA)
                        self.motor_b.Run(0, self.speedB)
                        self.motor_c.Run(0, self.trackingSpd)
                        self.pub_imagecommand.publish("start")
                        self.pub_lcd.publish("Start tracking \n status: %s" %(10))

                    elif last_data[0] == 'KEY_MUTE': # MUTE button - vse zastavi (vcetne hodinoveho stroje)
                        self.motor_a.Float()
                        self.motor_b.Float()
                        self.motor_c.Float()
                        self.flag['tracking']= False
                        self.pub_imagecommand.publish("stop")
                        self.pub_lcd.publish("STOP")
                        self.speedA = 0
                        self.speedB = 0
                        self.speedC = 0

                    elif last_data[0] == 'KEY_HOME': # HOME button - navrati coelostat do polohy, kde bude 'prenocovavat'
                        self.pub_imagecommand.publish("recenter")

                    elif last_data[0] == 'KEY_BACK': # BACK - vyresetuje nastavení, vycentruje obraz na střed
                        self.trackingSpdDefault = int(rospy.get_param("/coelostat/speeds/tracking", 100))
                        self.trackingSpd = self.trackingSpdDefault
                        self.motor_c.Run(0, self.trackingSpd)
                        print "back"


                    elif last_data[0] == 'KEY_NEXT': # + - None
                        pass


                
                else:
                    if last_data[0] == 'KEY_OK' and self.flag['tracking']== True:
                        pass
                        try:
                            print "tracking"

                            spdA = self.sunerr.x if self.sunerr.x < 50 else 50
                            spdB = self.sunerr.y if self.sunerr.y < 50 else 50

                            if abs(spdAold - spdA) > 0.9:
                                self.motor_a.Run(0, spdA)
                                spdAold = spdA
                            if abs(spdBold - spdB) > 0.9:
                                self.motor_b.Run(0, spdB)
                                spdBold = spdB
                        except Exception as e:
                            print 'err3>', e


                    #self.pymlab(device="gpio_mount", method="set_ports", parameters=str(dict(port0 = self.port0, port1= self.port1)))
                
            except Exception, e:
                print "err1>", e
            rate.sleep()


        self.motor_a.Float()
        self.motor_b.Float()
        self.motor_c.Float()

    def get_status(self, timer):
        try:
            self.motor_a_status = self.motor_a.GetStatus()
            self.motor_b_status = self.motor_b.GetStatus()
            self.motor_c_status = self.motor_c.GetStatus()

            self.pub_motor_a.publish(json.dumps(self.motor_a_status, ensure_ascii=False))
            self.pub_motor_b.publish(json.dumps(self.motor_b_status, ensure_ascii=False))
            self.pub_motor_c.publish(json.dumps(self.motor_c_status, ensure_ascii=False))
            
            #print self.motor_a_status['SW_F'], self.motor_b_status['SW_F'], self.motor_c_status['SW_F']
            if self.motor_a_status['SW_F'] | self.motor_b_status['SW_F'] | self.motor_c_status['SW_F']:
                print "Err"
                self.pub_beep.publish('horn')

        except Exception as e:
            print 'err2> ', e
            self.pub_beep.publish('horn')



    def callback_btn(self, recive):
        #print recive
        self.btn_data.append(recive.data)
        #print recive, btn_data

    def callback_sunerr(self, recive):
        #print recive
        self.sunerr = recive

        #self.btn_data.append(recive.data)
        #print recive, btn_data

    def callback_sunpos(self, recive):
        #print recive
        self.sunpos = recive


if __name__ == '__main__':
    m = SolarLab()