#!/usr/bin/env python
# -*- coding: utf-8 -*-

import evdev
from evdev import InputDevice, categorize, ecodes
from select import select
import time, os
import rospy
import std_msgs
import arom_helper

class user_input(arom_helper.AromNode):
    node_name = "Keyboard"
    node_type = "Keyboard"

    def __init__(self, name = "Keyboard"):
        print "starting Keyboard"
        print os.path.dirname(os.path.realpath(__file__))
        print os.getcwd()
        print __file__
        print "done"

        arom_helper.AromNode.__init__(self)
        self.set_feature('external',{'feature': __file__+".feature.hbs", 'type': "numerical", 'name': 'Keyboard', 'toppic_rx': "/ui"+rospy.get_name()+"/in/raw", 'layer': '/ui'+rospy.get_name()+'/layer'})
        self.btn_pub = rospy.Publisher('/ui'+rospy.get_name()+'/out', std_msgs.msg.String, queue_size=15, latch=False, tcp_nodelay=True)
        self.layer_pub = rospy.Publisher('/ui'+rospy.get_name()+'/layer', std_msgs.msg.String, queue_size=5, latch=True, tcp_nodelay=True)
        rospy.Subscriber("/ui"+rospy.get_name()+"/in/raw", std_msgs.msg.String, self.externalKey)

        print "btn_publisher:", '/ui'+rospy.get_name()+'/out'
        print "layer_publisher:", '/ui'+rospy.get_name()+'/layer'

        rate = rospy.Rate(10)


        devices = [evdev.InputDevice(fn) for fn in evdev.list_devices()]
        for device in devices:
            print(device.fn, device.name, device.phys)

        self.led_status = 0
        self.layer_count = 2
        self.toggle_button = 69
        self.setLayer()
        self.device1 = evdev.InputDevice('/dev/input/event6')
        self.device2 = evdev.InputDevice('/dev/input/event5')
        self.device1.grab()
        self.device2.grab()

        for i in range(10):
            self.toggleLED()
            time.sleep(0.1)

        keymap_patrola = [{
            172: 'shift',
            15:  'dome_a',
            155: 'dome_b',
            140: 'tracking_toggle',
            69: 'telescopeA_close',
            98: 'telescopeB_close',
            55: 'telescopeC_close',
            14: None,
            71: 'telescopeA_irisM',
            72: 'telescopeB_irisM',
            73: 'telescopeC_irisM',
            74: None,
            75: 'telescopeA_irisP',
            76: 'telescopeB_irisP',
            77: 'telescopeC_irisP',
            78: None,
            79: 'telescopeA_focusM',
            80: 'telescopeB_focusM',
            81: 'telescopeC_focusM',
            82: 'telescopeA_focusP',
            11: 'telescopeB_focusP',
            83: 'telescopeC_focusP',
            96: None,
        },{
            172: 'shift',
            15:  'dome_a',
            155: 'dome_b',
            140: 'tracking_toggle',
            69: 'RA_center',
            98: 'DEC_center',
            55: None,
            14: None,
            71: None,
            72: 'DEC_P',
            73: None,
            74: None,
            75: 'RA_P',
            76: None,
            77: 'RA_M',
            78: None,
            79: None,
            80: 'DEC_M',
            81: None,
            82: None,
            11: None,
            83: None,
            96: None,
        }]

        keymap_zvpp = [{
            69: 'shift',
            15:  None,
            155: None,
            140: None,
            690: None,
            98: None,
            51: 'A',
            55: None,
            14: 'gpio_3_toggle',
            71: None,
            72: 'DEC_P',
            73: None,
            74: 'B',
            75: 'RA_M',
            76: 'STOP',
            77: 'RA_P',
            78: 'C',
            79: None,
            80: 'DEC_M',
            81: None,
            82: None,
            11: None,
            83: None,
            96: None,
        },{
            69: 'shift',
            15:  None,
            155: None,
            140: None,
            690: None,
            98: None,
            51: 'A',
            55: None,
            14: 'gpio_3_toggle',
            71: None,
            72: 'DEC_P',
            73: None,
            74: 'B',
            75: 'RA_P',
            76: 'STOP',
            77: 'RA_M',
            78: 'C',
            79: None,
            80: 'DEC_M',
            81: None,
            82: None,
            11: None,
            83: None,
            96: None,
        }]
        

        #self.keymap = keymap_patrola
        self.keymap = keymap_zvpp

        data = []

        while not rospy.is_shutdown():
            for dev in [self.device1.read(), self.device2.read()]:
                try:
                    while True:
                        dev_out = dev.next()
                        if dev_out.type == ecodes.EV_KEY and dev_out.value in [0,1]:
                            print(dev_out)
                            data.append(self.GetKey(dev_out))
                except Exception as e:
                    pass

            rate.sleep()


    def GetKey(self, event):
        if event.code == self.toggle_button:
            if event.value == 1:
                layer = self.toggleLayer()
                self.toggleLED()
                self.btn_pub.publish("layer"+str(layer))
        else:
            key = self.keymap[self.layer][event.code]
            if key:
                self.btn_pub.publish(str(key)+str(event.value))
                self.blikLED()
                print "KEY:", (key, event.value)
                return (key, event.value)
            else:
                print "Klavesa nenastavena"

    def externalKey(self, event):
        print event
        value = {'d': 1L, 'u': 0L}[event.data[-1]]
        code = int(event.data[:-1])
        print code, value

        if code == self.toggle_button:
            if value == 1:
                layer = self.toggleLayer()
                self.toggleLED()
                self.btn_pub.publish("layer"+str(layer))
        else:
            key = self.keymap[self.layer][code]
            if key:
                self.btn_pub.publish(str(key)+str(value))
                self.blikLED()
                print "KEY:", (key, value)
                return (key, value)
            else:
                print "Klavesa nenastavena"

    def setLayer(self, layer = 0):
        self.layer = layer
        if self.layer >= self.layer_count:
            self.layer = self.layer_count
        self.layer_pub.publish(str(self.layer))
        print "Layer set to:", self.layer
        return self.layer

    def toggleLayer(self, step = +1):
        self.layer += step
        if self.layer >= self.layer_count:
            self.layer = 0
        self.layer_pub.publish(str(self.layer))
        print "Layer toggled to:", self.layer
        return self.layer

    def toggleLED(self):
        self.setLED(not bool(self.led_status))

    def setLED(self, status = 1):
        #print "LED", status
        self.device1.set_led(0, bool(status))
        self.led_status = status
        return bool(self.led_status)

    def blikLED(self, duration=0.1):
        self.toggleLED()
        time.sleep(duration)
        self.toggleLED()


if __name__ == '__main__':
    ui = user_input()
